_wandb:
    value:
        cli_version: 0.21.3
        e:
            mlzpg7nm3x5vr1xgfn3ry1z5exmtu83i:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1999481335808"
                        used: "636208279552"
                email: yongjae9@kaist.ac.kr
                executable: C:\ProgramData\anaconda3\envs\RSS_1st\python.exe
                git:
                    commit: c3f9679a2c34f161b49661a774153ed41b3939a1
                    remote: https://github.com/YongJaeKim99/RCMPSP_1st.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-e23d57fd-a2e5-1ee6-7e72-05da5a435e4b
                host: DESKTOP-6HI95GN
                memory:
                    total: "66195468288"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\yongjae\Desktop\Independent_research\RCMPSP\RCMPSP_1st\train.py
                python: CPython 3.13.5
                root: C:\Users\yongjae\Desktop\Independent_research\RCMPSP\RCMPSP_1st
                startedAt: "2026-02-11T10:05:53.194106Z"
                writerId: mlzpg7nm3x5vr1xgfn3ry1z5exmtu83i
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 13
                - 16
                - 61
            "4": 3.13.5
            "5": 0.21.3
            "8":
                - 3
            "12": 0.21.3
            "13": windows-amd64
N_A_max:
    value: 6
N_A_min:
    value: 4
N_P:
    value: 5
N_T:
    value: 4
algorithm:
    value: REINFORCE
batch_size:
    value: 16
embedding_dim:
    value: 128
entropy_coef:
    value: 0
epochs:
    value: 200
learning_rate:
    value: 3e-05
normalize_advantage:
    value: false
num_encoder_layer:
    value: 3
num_head:
    value: 8
objective:
    value: tardiness
pomo_size:
    value: 8
