_wandb:
    value:
        cli_version: 0.21.3
        e:
            1aw3p8ylf3ikq71rq6ndw1ldbjc7djqh:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1999481335808"
                        used: "756251181056"
                email: yongjae9@kaist.ac.kr
                executable: C:\ProgramData\anaconda3\envs\RSS_1st\python.exe
                git:
                    commit: 9e0986fec9d815def172b4c652d3fff1eccd679a
                    remote: https://github.com/YongJaeKim99/RCMPSP_1st.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-e23d57fd-a2e5-1ee6-7e72-05da5a435e4b
                host: DESKTOP-6HI95GN
                memory:
                    total: "66195468288"
                os: Windows-11-10.0.26100-SP0
                program: c:\Users\yongjae\Desktop\Independent_research\RCMPSP\RCMPSP_1st\train.py
                python: CPython 3.13.5
                root: C:\Users\yongjae\Desktop\Independent_research\RCMPSP\RCMPSP_1st
                startedAt: "2026-02-24T03:54:44.015528Z"
                writerId: 1aw3p8ylf3ikq71rq6ndw1ldbjc7djqh
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.13.5
            "5": 0.21.3
            "8":
                - 3
            "12": 0.21.3
            "13": windows-amd64
N_A_max:
    value: 6
N_A_min:
    value: 4
N_P:
    value: 10
N_T:
    value: 5
algorithm:
    value: REINFORCE
batch_size:
    value: 64
entropy_coef:
    value: 0
epochs:
    value: 1000
fea_act_input_dim:
    value: 14
fea_team_input_dim:
    value: 8
layer_fea_output_dim:
    value:
        - 32
        - 8
learning_rate:
    value: 0.0003
model_type:
    value: daniel
normalize_advantage:
    value: true
objective:
    value: tardiness
pomo_size:
    value: 4
reward_type:
    value: sparse
